### ISSUE TITLE
setTimeout in seeding

### ISSUE THREAD

**Issue by magnusriga** [atherosai/graphql-gateway-apollo-express#1]
@atherosai ,

Thanks for a great demo.

Quick question: How come you do a 50ms timeout when seeding the database? Wouldn't it be better to just return Promise.all( mapResult )?

**Comment by a7v8x** [comment]
Hi, thanks for writing I have not noticed the issue. I have closed this now as it was updated to creating objects in bulk, which should be faster once working with a real database.
